# Generated by Django 5.0.7 on 2024-07-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_image', models.ImageField(upload_to='content_images/')),
                ('style_image', models.ImageField(upload_to='style_images/')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='output_images/')),
            ],
        ),
    ]
